#!/usr/bin/env python
# coding:utf-8
# upper fasta sequences
#

import sys
import argparse

parser = argparse.ArgumentParser(
description="""
upper fasta sequences""",
epilog="""
With no FILE, or when FILE is -, read standard input.

Examples:
  fa-upper f      upper sequmences in f file
  fa-upper        upper sequmences standard input to standard output.

Report bugs to luyulinvip@outlook.com
""",
formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("file", nargs="?")
args = parser.parse_args()


builtin_print = print
def print(*args, **kwargs):
    try:
        builtin_print(*args, **kwargs)
    except (BrokenPipeError, IOError):
        exit()


inf = sys.stdin if args.file is None or args.file == "-" else open(args.file, "r")
for line in inf:
    if line[0] == ">":
        print(line.strip())
    else:
        print(line.upper().strip())
inf.close()

