#!/usr/bin/env python
# coding:utf-8
# transpose data matrix (swap rows and columns)
#

import sys
import argparse

parser = argparse.ArgumentParser(
description="""
Transpose data matrix (Swap rows and columns)""",
epilog="""
With no FILE, or when FILE is -, read standard input.

Examples:
  trs f      transpose f file
  trs        transpose standard input to standard output.

Report bugs to luyulinvip@outlook.com
""",
formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("file", nargs="?")
args = parser.parse_args()

data = []

inf = sys.stdin if args.file is None or args.file == "-" else open(args.file, "r")
for line in inf:
    data.append([i.strip() for i in line.strip("\n").split("\t")])
inf.close()

nrow = len(data)
if nrow == 0:
    exit()
ncol = len(data[0])
if ncol == 0:
    exit()

for i in range(ncol):
    print("\t".join([d[i] for d in data]))

